import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { join, basename } from "node:path";

const TEMPLATE_INDEX_JS = `// Generated by Wish

/**
 * Entry point for the application.
 */
export async function start() {
  console.log("Hello from Wish!");
}

import { fileURLToPath } from 'node:url';

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  start().catch(console.error);
}
`;

const TEMPLATE_INDEX_TEST_JS = `import { test } from 'node:test';
import assert from 'node:assert/strict';
import { start } from './index.js';

test('initializes correctly', async () => {
  assert.ok(typeof start === 'function', 'start is exported');
});
`;

/**
 * Seeds an empty output directory with a definitive boilerplate ES Module structure.
 * This establishes strict stylistic rules (import/export, node:test usage, async/await native)
 * directly in the LLM's context window.
 *
 * @param {string} outputDir Absolute path to the output directory
 * @param {string} projectDir Absolute path to the project directory (used for deriving the name)
 */
export function injectBoilerplate(outputDir, projectDir) {
  // Only inject if the directory does not exist entirely.
  if (existsSync(outputDir)) {
    return;
  }

  const projectName =
    basename(projectDir)
      .toLowerCase()
      .replace(/[^a-z0-9-]/g, "-") || "wish-app";

  const packageJson = {
    name: projectName,
    version: "1.0.0",
    type: "module",
    scripts: {
      start: "node index.js",
      test: "node --test",
    },
    dependencies: {},
  };

  mkdirSync(outputDir, { recursive: true });

  writeFileSync(
    join(outputDir, "package.json"),
    JSON.stringify(packageJson, null, 2) + "\n",
    "utf-8",
  );
  writeFileSync(join(outputDir, "index.js"), TEMPLATE_INDEX_JS, "utf-8");
  writeFileSync(
    join(outputDir, "index.test.js"),
    TEMPLATE_INDEX_TEST_JS,
    "utf-8",
  );
}
